# The coco2017 dataset with instance, stuff and caption annotations.
_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/coco14_task3/train/shard-{000000..000151}.tar"
train_size: 68750
val_shards: "${oc.env:DATASET_PREFIX}/coco14_task3/val/shard-{000000..000151}.tar"
val_size: 68750
test_shards: "${oc.env:DATASET_PREFIX}/coco14/test/shard-{000000..000126}.tar"
test_size: 40670
use_autopadding: true