# The PASCAL VOC 2012 dataset, using joint train+val splits for training and validation.
# This setting is often used in the unsupervised case.
_target_: ocl.datasets.WebdatasetDataModule
train_shards:
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000000.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000001.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000002.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000003.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000004.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000005.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000006.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000007.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000008.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000009.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000010.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000011.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000012.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000013.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000014.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000015.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000016.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000017.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000018.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000019.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000020.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000021.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000000.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000001.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000002.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000003.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000004.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000005.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000006.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000007.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000008.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000009.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000010.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000011.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000012.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000013.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000014.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000015.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000016.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000017.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000018.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000019.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000020.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000021.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000022.tar"
train_size: 11540
val_shards:
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000000.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000001.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000002.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000003.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000004.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000005.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000006.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000007.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000008.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000009.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000010.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000011.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000012.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000013.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000014.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000015.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000016.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000017.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000018.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000019.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000020.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/train/shard-000021.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000000.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000001.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000002.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000003.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000004.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000005.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000006.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000007.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000008.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000009.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000010.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000011.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000012.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000013.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000014.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000015.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000016.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000017.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000018.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000019.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000020.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000021.tar"
  - "${oc.env:DATASET_PREFIX}/voc2012_detection/val/shard-000022.tar"
val_size: 11540
test_shards: "${oc.env:DATASET_PREFIX}/voc2012_detection/test/shard-{000000..000041}.tar"
test_size: 10991
use_autopadding: true
