repos:
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  -   id: absolufy-imports
- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    require_serial: true
    types: [python]
  - id: black
    name: black
    entry: poetry run black
    language: system
    require_serial: true
    types: [python]
  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    require_serial: true
    types: [python]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=750']
  - id: check-merge-conflict
