# @package _global_
# Metrics for object discovery on COCO/VOC with instance masks.
evaluation_metrics:
  instance_mask_ari:
    _target_: routed.ocl.metrics.ARIMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    foreground: false
    convert_target_one_hot: true
    ignore_overlaps: true
  instance_mask_unsup_iou:
    _target_: routed.ocl.metrics.UnsupervisedMaskIoUMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_mask_abo:
    _target_: routed.ocl.metrics.AverageBestOverlapMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_mask_corloc:
    _target_: routed.ocl.metrics.MaskCorLocMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
  instance_mask_recall:
    _target_: routed.ocl.metrics.BestOverlapObjectRecoveryMetric
    prediction_path: masks_resized
    target_path: input.instance_mask
    ignore_overlaps: true
