# @package _global_
dataset:
  eval_transforms:
    02a_format_consistency:
      _target_: ocl.transforms.Map
      transform:
        _target_: ocl.preprocessing.RenameFields
        mapping:
          objects.bbox: instance_bbox

      fields:
        - objects.bbox
      batch_transform: false
    03a_preprocessing:
      _target_: ocl.transforms.Map
      transform:
        _target_: torchvision.transforms.Compose
        transforms:
          - _target_: ocl.preprocessing.AddImageSize
          - _target_: ocl.preprocessing.CanonicalizeBboxes
            format: yxyx
          - _target_: ocl.preprocessing.RescaleBboxes
          - _target_: ocl.preprocessing.AddEmptyBboxes

      fields:
        - image
      batch_transform: false
    03b_preprocessing:
      _target_: ocl.transforms.SimpleTransform
      transforms:
        image:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: torchvision.transforms.ToTensor
            - _target_: torchvision.transforms.Resize
              _convert_: all
              size: [224, 224]
              interpolation: ${torchvision_interpolation_mode:BICUBIC}
            - "${lambda_fn:'lambda image: image.clamp(0.0, 1.0)'}"
            - _target_: torchvision.transforms.Normalize
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      batch_transform: false
