# @package _global_
defaults:
  - /evaluation_clustering_config
  - /evaluation/projects/bridging/_base_clustering
  - /evaluation/projects/bridging/_classes_coco_coarse
  - /evaluation/projects/bridging/_preprocessing_coco_27
  - /dataset: coco_nocrowd
  - _self_

batch_size: 32
n_classes: 27
ignore_background: true
use_ignore_masks: true

representation_type: RepresentationType.MASK_WEIGHTED_FEATURES

clusterings:
  kmeans27_l2:
    _target_: ocl.metrics.SklearnClustering
    n_clusters: 27
    method: kmeans
    use_l2_normalization: true
    clustering_kwargs:
      n_init: 20
