# @package _global_
# Evaluate on MOVi-E with slot attention

defaults:
  - /evaluation_config
  - /evaluation/projects/bridging/_base_metrics
  - /evaluation/projects/bridging/_preprocessing_movi_e
  - /evaluation/projects/bridging/_metrics_discovery_movi
  - /dataset: movi_e_image
  - _self_

eval_batch_size: 16

modules:
  masks_resized:
    size_tensor_path: input.mask
    patch_mode: false

plugins:
  03_preprocessing:
    evaluation_transforms:
      image:
        _target_: torchvision.transforms.Compose
        transforms:
          - _target_: torchvision.transforms.ToTensor
          - _target_: torchvision.transforms.Normalize
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
