# @package _global_
# Evaluate bounding boxes and masks on COCO at original image resolution.
defaults:
  - /evaluation_config
  - /evaluation/projects/bridging/_base_metrics
  - /evaluation/projects/bridging/_preprocessing_coco
  - /evaluation/projects/bridging/_metrics_discovery_masks
  - /evaluation/projects/bridging/_metrics_discovery_bboxes
  - /dataset: coco_nocrowd
  - _self_

eval_batch_size: 1
