# @package _global_
# Evaluate random masks on MOVi (applied to slot attention model).

defaults:
  - /evaluation_config
  - /evaluation/projects/bridging/_base_metrics
  - /evaluation/projects/bridging/_preprocessing_movi_c
  - /evaluation/projects/bridging/_metrics_discovery_movi
  - /dataset: movi_c_image
  - _self_

eval_batch_size: 16

modules:
  masks_resized:
    size_tensor_path: input.mask
    patch_mode: false

  random_masks:
    _target_: routed.ocl.utils.masking.CreateRandomMaskPatterns
    masks_path: masks_resized
    pattern: blocks
    n_slots: 11
    n_cols: 3

evaluation_metrics:
  ari:
    prediction_path: random_masks
    target_path: input.mask
  abo:
    prediction_path: random_masks
    target_path: input.mask

plugins:
  03_preprocessing:
    evaluation_transforms:
      image:
        _target_: torchvision.transforms.Compose
        transforms:
          - _target_: torchvision.transforms.ToTensor
          - _target_: torchvision.transforms.Normalize
            mean: [0.5, 0.5, 0.5]
            std: [0.5, 0.5, 0.5]
