# @package _global_
# Save model predictions on MOVi datasets
dataset:
  eval_transforms:
    03_preprocessing:
      _target_: ocl.transforms.Map
      transform: "${lambda_fn:'lambda data: {\"orig_image\": data[\"image\"], **data}'}"
      fields:
        - image
      batch_transform: false
    04_preprocessing:
      _target_: ocl.transforms.SimpleTransform
      transforms:
        orig_image:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: torchvision.transforms.ToTensor
        image:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: torchvision.transforms.ToTensor
            - _target_: torchvision.transforms.Resize
              size: 224
              interpolation: ${torchvision_interpolation_mode:BICUBIC}
            - "${lambda_fn:'lambda image: image.clamp(0.0, 1.0)'}" # Bicubic interpolation can get out of range
            - _target_: torchvision.transforms.Normalize
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
        mask:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: ocl.preprocessing.MultiMaskToTensor
            - _target_: ocl.preprocessing.ResizeNearestExact
              size: 128
      batch_transform: false
defaults:
  - /evaluation_config
  - /evaluation/projects/bridging/_base_metrics
  - /dataset: movi_e_image
  - _self_

eval_batch_size: 1

save_outputs: true
skip_metrics: true
n_samples_to_store: 100
outputs_to_store:
  - input.orig_image
  - input.mask
  - masks_resized

modules:
  masks_resized:
    size_tensor_path: input.mask
