# @package _global_
# Metrics for object discovery with instance masks.
evaluation_metrics:
  ari:
    _target_: routed.ocl.metrics.ARIMetric
    prediction_path: masks_resized
    target_path: input.mask
  abo:
    _target_: routed.ocl.metrics.AverageBestOverlapMetric
    prediction_path: masks_resized
    target_path: input.mask
    ignore_background: true
