# @package _global_
# Config file used with eval
defaults:
  - /evaluation_config
  - /evaluation/slate/_preprocessing_coco
  - /evaluation/slate/_metrics_masks
  - /dataset: coco
  - _self_

eval_batch_size: 1
